### PR TITLE
Add preview action to gitn_log kind

### PR DESCRIPTION
**Pull request by kmnk**
It works.

But should be more beautiful code. If I get more time, re-implment.

### CODE REVIEW

**Comment by petobens** [comment]
Hi! Thanks for working on this. I'm trying the feature but I'm seeing the following error:
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 132, in _start
[denite]     self.update_buffer()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 410, in update_bu
ffer
[denite]     self.move_cursor()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 533, in move_curs
or
[denite]     self.do_action('preview')
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 696, in do_action

[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 315, in do_action
[denite]     return action['func'](context) if action['func'] else self._vim.call(
[denite]   File "/Users/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/kind/gitn_log.py", line 136, in action_preview
[denite]     self.vim.command('keepjumps normal G')
[denite]   File "/usr/local/lib/python3.7/site-packages/neovim/api/nvim.py", line 272, in command
[denite]     return self.request('nvim_command', string, **kwargs)
[denite]   File "/usr/local/lib/python3.7/site-packages/neovim/api/nvim.py", line 170, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.7/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(normal):E490: No fold found'
[denite] Please execute :messages command.
```

**Comment by kmnk** [comment]
fold ... ?

OK. I will check it when get time.

Can you give me more information ?

- If you use without `-auto-preview` option, when does error occur ?
    - when call `Denite gitn_log` ?
    - when execute `preview` action of log line ?
- Occurs every-repositories or by repositories ?
- What your fold method is ?
    - You can see by executing `:set foldmethod?` command

Thanks

**Comment by petobens** [comment]
Thank you. I''ll try to find a simple way of reproducing and report back.

**Comment by petobens** [comment]
Ok, I think I fixed my previous issue in the linked PR. One further thing I've noticed is that the preview doesn't seem to respect the `-vertical-preview` flag/modifier as in:
```
nnoremap <silent> <Leader>gl :Denite -auto-preview -default-action=diff
            \ -vertical-preview gitn_log:*:current<CR>
```
Any chance of implementing that? Thanks (and sorry for being such a nuisance)

**Comment by petobens** [comment]
Another minor thing not related to preview: when executing `diff` action on a candidate a new buffer is opened without name i.e `[No Name]`. Can the buffer actually have the first 7 characters of the commit hash?

**Comment by kmnk** [comment]
Thanks for providing many information and patch.

> Any chance of implementing that?

OK.. but I don't have good idea for resolving this problem.
I might take  a long time to resolve it ..

> when executing diff action on a candidate a new buffer is opened without name i.e [No Name]. Can the buffer actually have the first 7 characters of the commit hash?

That certainly is very clear for checking diff.
I'm thinking about way to it, too.

Now, I create new issues for tracking above problem and idea.

- https://github.com/kmnk/gitn/issues/13
- https://github.com/kmnk/gitn/issues/14

If I making progress, I add comment to those issues !

**Comment by petobens** [comment]
Thanks for opening the issues!

**Pull request merged**
